version: "3.9"

services:
  preview:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlpreview
    hostname: sqlpreview
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Simple123"
      MSSQL_PID: "Evaluation"
    restart: unless-stopped
